# UTF-8 support for compatibility
charset utf-8

# No comments in messages
no-comments

# No version in output
no-emit-version

# Disable banner
no-greeting

# Long key id format
keyid-format 0xlong

# Display UID validity
list-options show-uid-validity
verify-options show-uid-validity

# Display all keys and their fingerprints
with-fingerprint

# Cross-certify subkeys are present and valid
require-cross-certification

# Disable caching of passphrase for symmetrical ops
no-symkey-cache

# Enable smartcard
use-agent
