[env]
# TERM = "xterm-256color"

[window]

[font]
size = 10.5

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
style = "Bold"

[font.italic]
style = "Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
