#!/bin/sh

notmuch tag +info-gnu +maillist -- cc:info-gnu@gnu.org or to:info-gnu@gnu.org
notmuch tag +info-guix +maillist -- cc:info-guix@gnu.org or to:info-guix@gnu.org
notmuch tag +help-guix +maillist -- cc:help-guix@gnu.org or to:help-guix@gnu.org
notmuch tag +sg7 +maillist -- cc:sg7@lists.isocpp.org or to:sg7@lists.isocpp.org
notmuch tag +sg13 +maillist -- cc:sg13@lists.isocpp.org or to:sg13@lists.isocpp.org
notmuch tag +sg14 +maillist -- cc:sg14@lists.isocpp.org or to:sg14@lists.isocpp.org
notmuch tag +sg15 +maillist -- cc:sg15@lists.isocpp.org or to:sg15@lists.isocpp.org
notmuch tag +sg16 +maillist -- cc:sg16@lists.isocpp.org or to:sg16@lists.isocpp.org
notmuch tag +std-discussion +maillist -- cc:std-discussion@lists.isocpp.org or to:std-discussion@lists.isocpp.org
notmuch tag +std-proposals +maillist -- cc:std-proposals@lists.isocpp.org or to:std-proposals@lists.isocpp.org
notmuch tag +notmuch +maillist -- cc:notmuch@notmuchmail.org or to:notmuch@notmuchmail.org
notmuch tag +rjarry-aerc-discuss +maillist -- cc:~rjarry/aerc-discuss@lists.sr.ht or to:~rjarry/aerc-discuss@lists.sr.ht
notmuch tag +pgsql-general +maillist -- cc:pgsql-general@lists.postgresql.org or to:pgsql-general@lists.postgresql.org
notmuch tag +pgsql-general +maillist -- cc:pgsql-general@postgresql.org or to:pgsql-general@postgresql.org
notmuch tag +boost-users +maillist -- cc:boost-users@lists.boost.org or to:boost-users@lists.boost.org
notmuch tag +boost +maillist -- cc:boost@lists.boost.org or to:boost@lists.boost.org
notmuch tag +zsh-users +maillist -- cc:zsh-users@zsh.org or to:zsh-users@zsh.org

# Some interesting trashing/trashed, Xing/Xed in general was mentioned

notmuch tag -inbox -unread +trash -- folder:Trash
notmuch tag -inbox -unread +spam -- folder:Spam
notmuch tag -inbox -unread -draft +sent -- folder:Sent
notmuch tag -inbox -unread +draft -- folder:Draft

notmuch tag +inbox -- folder:INBOX

notmuch search --format=text0 --output=files tag:trash | xargs -0 --no-run-if-empty rm -v
